# show aws
[aws]
disabled = false
force_display = true

# hide gcloud for now
[gcloud]
disabled = true

# mere preference
[git_branch]
symbol = "Ôêò "

# helm module offers no value to me
[helm]
disabled = true

# show kubernetes
[kubernetes]
disabled = false
style = "yellow"

# python module offers no value to me
[python]
disabled = true

# terraform module offers no value to me
[terraform]
disabled = true
