# prepend the whole thing with the value of INVENTORY, if present
format = '${env_var.INVENTORY}$all'

# show aws
[aws]
disabled = false
force_display = true
style = "yellow"
symbol = ''

# cloud identifier
[env_var.INVENTORY]
style = "green"
format = '[$env_value]($style) '

# hide gcloud
[gcloud]
disabled = true

# mere preference
[git_branch]
symbol = "Ôêò "

# helm module offers no value to me
[helm]
disabled = true

# kubernetes with shortened context names
[kubernetes]
disabled = false
style = "yellow"
symbol = ''
[[kubernetes.contexts]]
context_pattern = 'arn.*\/(?P<cluster>[\w\/-]+)'
context_alias = "$cluster"
[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<cluster>[\\w-]+)"
context_alias = "$cluster"

# nodejs module offers no value to me
[nodejs]
disabled = true

# python module offers no value to me
[python]
disabled = true

# terraform module offers no value to me
[terraform]
disabled = true
